services:
  mat-o-wahl:
    container_name: mat-o-wahl
    image: ghcr.io/msteudtn/mat-o-wahl:latest # you can also use the dockerhub image  msteudtn/mat-o-wahl:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html/data
      - ./extras:/var/www/html/extras