name: Build and Push Docker Image to github registry

on:
  push:
    branches:
    - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Get latest release tag
          id: get_latest_release
          uses: pozetroninc/github-action-get-latest-release@master
          with:
            owner: msteudtn
            repo: mat-o-wahl
          
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: log in to Github Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}

        - name: 'Build and push Docker image'
          run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 . --tag ghcr.io/msteudtn/mat-o-wahl:latest --tag ghcr.io/mat-o-wahl:${{ steps.get_latest_release.outputs.release }} --push